### ISSUE TITLE
Problem with responsive navbar

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#122]
When changing the size of the site window, the sidebar adapts to be responsive, also adding the elements at the top in the menu. But, when we put it back normally, the elements which were added in the menu, do not withdraw totally ...

The test in the image were done on the creative-tim demo.

Regards,

![sidebar](https://user-images.githubusercontent.com/27307704/38264042-dabd570a-373f-11e8-9eff-c6ed5c1bf41f.gif)

**Comment by FeddyCastro** [comment]
I have the same problem partner, I want to know if they already solved it thanks ..?

**Comment by dragosct10** [comment]
Hi! Thank for using our product. To fix this temporary you can add on the class .nav-mobile-menu the property `display: none;` on the min-width: 991px like example below. We will fix this in the next update. 

```css
@media screen and (min-width: 991px) {
    .nav-mobile-menu {
        display: none;
    }
}
```

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi, @killer3dfx! What part did you not find? Regards, Dragos

**Comment by killer3dfx** [comment]
Hello, I cant find the following in material-dashboard.css

@media screen and (min-width: 991px) {
    .nav-mobile-menu {

**Comment by dragosct10** [comment]
Hi, @killer3dfx! That lines of code you will not find in the material-dashboard.css because you must add them. Regards, Dragos

**Comment by killer3dfx** [comment]
The fix did not work for me.

the problem is when I maximize the window after Navbar was hidden.

**Comment by dragosct10** [comment]
Hi, @killer3dfx! Please, can you show us how looks your code? Regards, Dragos

**Comment by mtik00** [comment]
I needed to add `!important`.  I.e., in "assets-for-demo/demo.css" I added this code (css noob here):
```css
@media screen and (min-width: 991px) {
    .nav-mobile-menu {
        display: none !important;
    }
}
```

This mostly works, however the "Search" form sometimes gets left behind:
![image](https://user-images.githubusercontent.com/1509355/38769177-d84e79fc-3fbb-11e8-8e1a-710469cb9f56.png)

I tried adding `.navbar-form {display: none !important;}` to the block above (demo.css), but that hid the search bar from >991px too.

**Comment by dragosct10** [comment]
Hi, @mtik00! Thank you for using our product. Your code to hide the navbar form from sidebar  must be like this: 

```css
@media screen and (min-width: 991px) {
    .sidebar .navbar-form {
        display: none !important;
    }
}
```
Regards,
Dragos
