### ISSUE TITLE
Sidebar from left

### ISSUE THREAD

**Issue by wellwind** [creativetimofficial/ct-material-dashboard-pro#13]
I have just purchased material-dashboard-pro, currently when window size < 991 the sidebar will hide to right, is it possible to set it to left?

thanks

**Comment by alexandru-paduraru** [comment]
@wellwind thank you for using our product. At this moment that feature is not implemented. Stay tuned, we will come with a solution in the next 1-2 days.

CC: @dragosct10 

Best,
Alex

**Comment by dragosct10** [comment]
Hello @wellwind! Please follow the next steps: 

1.First you must to go on html page and add to body tag the class `menu-on-left`.

2.Second go to `assets/sass/md/_responsive.scss` and add the following lines of code:

```css

@media (max-width: 991px){

.menu-on-left{

&.nav-open{

.main-panel,

.wrapper-full-page,

.navbar-fixed > div{

@include transform-translate-x(260px);

}

.sidebar,

.off-canvas-sidebar{

@include transform-translate-x(0px);

}

}

.sidebar,

.off-canvas-sidebar{

left: 0;

right: auto;

@include transform-translate-x(-260px);

}

}

}

```

3. Compile your scss with [Koala](http://koala-app.com/) assets/scss/paper-dashboard.scss.

4. Go to `assets/js/material-dashboard.js` and add the following code on line 85 and line 163, then go to the following lines: 339, 363 and 375. You have to replace `$('html')` with `$('body')`:

```js

line 84: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){

$('.main-panel').css('position','fixed');

}

line 97: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){

$('.main-panel').css('position','fixed');

} else {

$('.main-panel').css('position','');

}

```
