### ISSUE TITLE
SelectPicker data-color not applied properly

### ISSUE THREAD

**Issue by sophoulis** [creativetimofficial/ct-material-dashboard-pro#81]
It seems when I use a Selectpicker in Material Dashboard Pro inside a wizard card, the colour selected using data-color is not applied correctly to the listed options. See below my html code and attached a screenshot with the issue

Wizard card --> div class="card wizard-card" data-color="blue" id="wizardProfile"
Select Input -->  select class="selectpicker" required="true" data-style="select-with-transition" title="Choose Technology" data-size="7"

![materialdashboard_issue](https://user-images.githubusercontent.com/1002462/32883283-35658b96-cab7-11e7-8da9-a281d384c719.png)

**Comment by sophoulis** [comment]
Hi any news on this one? Have you managed to reproduce it @dragosct10 ?

**Comment by dragosct10** [comment]
Hi @sophoulis! Thank you for using our product and we are sorry for the late response, it was a busy period for us. To fix this issue for you please go in your project in `assets/sass/material-dashboard/_mixins.scss` partial and search inside of this partial for `set-wizard-color`. You will find an mixin and inside of this mixin please add the following code:

```css
    .dropdown-menu li a:hover,
    .dropdown-menu li a:focus,
    .dropdown-menu li a:active{
        background-color: $color;
    }

    .bootstrap-select.btn-group .dropdown-menu li a:focus,
    .bootstrap-select.btn-group .dropdown-menu li a:hover{
        @include shadow-big-color($color);
    }
```

After you will do this please compile you scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/material-dashboard.css`.

Regards,
Dragos
